IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_NAME='User' AND TABLE_SCHEMA='dbo')
BEGIN
	DROP TABLE [User]
END
ELSE
BEGIN
	SELECT 'THE TABLE DID NOT EXITS'
END

CREATE TABLE [User](
	[ID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[CreatedDate] DATETIME NOT NULL,
	[CreatedByUserID] UNIQUEIDENTIFIER NOT NULL,
	[ModifiedDate] DATETIME NOT NULL, 
	[ModifiedByUserID] UNIQUEIDENTIFIER NOT NULL,
	[UserName] VARCHAR(50),
	[Password] VARCHAR(50),
)

SELECT 'TABLE IS CREATED'